

#docker-compose up -d
#docker-compose ps
#docker-compose down --volumes


#docker stack deploy --compose-file docker-compose.yml stackdemo
#docker stack services stackdemo


version: '3.3'

services:
  app:
    container_name: phpfpm
    image: aregsar/phpfpm-prod
    volumes:
        - storage:/var/www/storage
    env_file: '.env.prod'
  web:
    container_name: nginx
    image: aregsar/nginx-prod
    ports:
      - 8080:80
      - 443:443

volumes:
  storage:



 