#test commands to build and run this dockerfile
#docker build . -f Dockerfile-app -t aregsar/phpfpm-prod
#docker run -p 9000:9000 aregsar/phpfpm-prod

#todo: add bootstrap/cache/* to dockerignore?


#
# build stage 
#
FROM composer:1.6.3 AS build

WORKDIR /app

#only copy composer files so we won't install deps if other files change
COPY composer.json composer.lock ./

#composer autoloader needs to scan files in database directory
COPY database ./database

#create vendors directory and installs dependancies from composer.json
RUN composer install --no-scripts --no-interaction

#copy all required files and directories 
#COPY ./ ./
COPY storage ./storage
COPY resources/lang ./resources/lang
COPY public/index.php ./public/index.php
COPY bootstrap ./bootstrap
COPY public/mix-manifest.json ./public/mix-manifest.json
COPY config ./config
COPY routes ./routes
COPY resources/views ./resources/views
COPY app ./app

#uncomment test files in case we want to pass tests before image is built
#COPY tests ./tests
#COPY phpunit.xml ./phpunit.xml

#uncomment artisan if we want to use image to run artisan commands
#COPY artisan ./artisan

#
# run stage
#
FROM php:7.2.2-fpm-alpine

#todo: should do this in build stage and copy installed file from there
RUN docker-php-ext-install pdo_mysql

WORKDIR /var/www

#copy over built application
COPY --from=build /app ./

RUN chown -R www-data:www-data ./bootstrap/cache ./storage

EXPOSE 9000

CMD ["php-fpm"]